name: .NET

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run migrations
      id: run-migrations
      uses: GGrouppFoundation/infra-sql-migration@v0.0.6
      with:
        connection_string: ${{ secrets.DB_MIGRATION_CONNECTION_STRING }}
        config_path: 'db/migrations.yaml'