name: .NET

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Run migrations
      id: run-migrations
      uses: actions/sql-migration@v0.0.1
      with:
        connection-string: ${{ secrets.DB_MIGRATION_CONNECTION_STRING }}
        config-path: 'db/migrations.yaml'
        timeout: 00:05:00